### ISSUE TITLE
Type in warning message 'node_models'?

### ISSUE THREAD

**Issue by flcdrg** [jfrog/build-info-go#202]
### Describe the bug

In https://github.com/jfrog/build-info-go/blob/724a12dc781f24eddbc1547f1fe96509876c0b76/build/utils/npm.go#L78 a mention is made to "node_models". I've never heard of this, but I have heard of "node_modules". I wonder if this is a typo and it should say "node_modules"?

```go
             log.Warn("The following dependencies will not be included in the build-info, because they are missing in the npm cache: '" + strings.Join(otherMissingDeps, ",") + "'.\nHint: Try to delete 'node_models' and/or 'package-lock.json'.")
```

### Current behavior

Warning logged "Hint: Try to delete 'node_models' and/or 'package-lock.json'"

### Operating system type and version

Linux

**Comment by Or-Geva** [comment]
Thank you for your contribution, @flcdrg. Your PR has been merged.
